// server.js
const express = require('express');
const axios = require('axios');
const fs = require('fs').promises;
const fsSync = require('fs');
const { execSync, spawn } = require('child_process');
const { Storage } = require('@google-cloud/storage');
const path = require('path');

const app = express();
// Increased limit for larger JSON payloads
app.use(express.json({ limit: '200mb' })); 

const storage = new Storage();
// Ensure these environment variables are set in your Cloud Run/GKE deployment
const BUCKET = process.env.BUCKET_NAME || '';
const RENDER_SECRET = process.env.RENDER_SECRET || 'change_me';

// -------------------------
// Utility functions
// -------------------------
function runCommandSync(cmd) {
  // Utility for quick synchronous command execution (used for ffprobe)
  execSync(cmd, { stdio: 'inherit' });
}

function runFFmpeg(args) {
  // Promisified execution of ffmpeg command
  return new Promise((resolve, reject) => {
    const ff = spawn('ffmpeg', args, { stdio: 'inherit' });
    ff.on('close', code => {
      if (code === 0) resolve();
      else reject(new Error('ffmpeg exit code ' + code));
    });
  });
}

async function uploadToGCS(localPath, destName) {
  if (!BUCKET) throw new Error('BUCKET_NAME not set in env');
  const bucket = storage.bucket(BUCKET);
  // Upload file
  await bucket.upload(localPath, { destination: destName });

  const file = bucket.file(destName);

  // Create a signed URL valid for 7 days (max allowed by GCS)
  const expiresDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000); 
  const [signedUrl] = await file.getSignedUrl({
    version: 'v4',
    action: 'read',
    expires: expiresDate
  });

  return signedUrl;
}

function secToAss(tSec) {
  // Converts seconds (float) to ASS timestamp format H:MM:SS.cc
  const h = Math.floor(tSec / 3600);
  const m = Math.floor((tSec % 3600) / 60);
  const s = Math.floor(tSec % 60);
  const cs = Math.floor((tSec - Math.floor(tSec)) * 100);
  return `${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(cs).padStart(2,'0')}`;
}

function cssToAssColor(hex) {
  // Converts CSS hex color (#RRGGBB) to ASS color format (&HBBGGRR)
  // Handles common names and short hex.
  if (!hex || typeof hex !== 'string' || !hex.startsWith('#')) {
    return '&H00FFFFFF'; // Default to Opaque White
  }
  
  let r, g, b;
  
  if (hex.length === 7) { 
    r = hex.substring(1, 3);
    g = hex.substring(3, 5);
    b = hex.substring(5, 7);
  } else if (hex.length === 4) {
    r = hex.substring(1, 2).repeat(2);
    g = hex.substring(2, 3).repeat(2);
    b = hex.substring(3, 4).repeat(2);
  } else {
    return '&H00FFFFFF';
  }

  // ASS format is &H + Alpha (00 for Opaque) + Blue + Green + Red
  return `&H00${b}${g}${r}`.toUpperCase();
}


// ⭐ FIXES Applied in framesToAss:
// 1. MarginV adjusted to fix line swap (MarginV_Line1 > MarginV_Line2).
// 2. Alignment set to 2 (Bottom-Center) for clear relative positioning.
// 3. getPlainText ensures input lines are treated as single lines to prevent unexpected ASS auto-wrapping/splitting.
function framesToAss(frames, styles, playResX = 1920, playResY = 1080) {
  
  // Style 1 (TOP Line in final video)
  const font1 = (styles && styles.fontTop) || 'Lexend';
  const size1 = (styles && styles.fontSizeTop) || 64; // Default to a smaller size
  const color1Primary = cssToAssColor(styles && styles.colorTop);  
  const weight1 = (styles && (styles.fontWeightTop === '700')) ? '1' : '0';  
  const italic1 = (styles && styles.isItalicTop) ? '1' : '0';  

  // Style 2 (BOTTOM Line in final video)
  const font2 = (styles && styles.fontBottom) || 'Cormorant Garamond';
  const size2 = (styles && styles.fontSizeBottom) || 100;
  const color2Primary = cssToAssColor(styles && styles.colorBottom);  
  const weight2 = (styles && (styles.fontWeightBottom === '700')) ? '1' : '0';
  const italic2 = (styles && styles.isItalicBottom) ? '1' : '0';
  
  // Padding from the bottom edge for the BOTTOM LINE (Line 2)
  const marginV_Line2 = (styles && styles.paddingBottom) || 200;
  
  // MarginV for Line 1 (TOP LINE)
  // MarginV is distance from the bottom edge. 
  // Line 1 needs to be higher up, so it must have a LARGER MarginV value.
  const VERTICAL_GAP = 15; // Gap between the two lines
  const marginV_Line1 = marginV_Line2 + size2 + VERTICAL_GAP;  
  
  // Setup for consistent shadows/outlines
  const shadowColor = '&H80000000'; // 50% opaque black shadow color
  const outline = 0;  
  const shadow = 2; // Shadow distance
  
  const header = `[Script Info]
ScriptType: v4.00+
PlayResX: ${playResX}
PlayResY: ${playResY}
WrapStyle: 0
Title: Generated by AiVideoCaptioner

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: STYLE2,${font2},${size2},${color2Primary},${color2Primary},&H00000000,${shadowColor},${weight2},${italic2},0,0,100,100,0,0,1,${outline},${shadow},2,20,20,${marginV_Line2},1
Style: STYLE1,${font1},${size1},${color1Primary},${color1Primary},&H00000000,${shadowColor},${weight1},${italic1},0,0,100,100,0,0,1,${outline},${shadow},2,20,20,${marginV_Line1},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`;
  
  // Function to ensure input lines are treated as single text blocks
  const getPlainText = (lineText) => {
    // Replaces newlines with ASS newline tag \N if present, otherwise just trims
    return lineText ? lineText.trim().replace(/\n/g, '\\N') : '';
  };
  
  const events = frames.flatMap(f => {
    const startSec = (f.start || 0) / 1000;
    const endSec = (f.end || (startSec + 2000)) / 1000;
    const startAss = secToAss(startSec);
    const endAss = secToAss(endSec);
    
    const lines = [];
    
    // Line 1 (TOP) -> Uses STYLE1 (Higher MarginV -> higher on screen)
    if (f.line1 && f.line1.trim() !== '') {
      const text1 = getPlainText(f.line1);
      lines.push(`Dialogue: 0,${startAss},${endAss},STYLE1,,0,0,0,,${text1}`);
    }
    
    // Line 2 (BOTTOM) -> Uses STYLE2 (Lower MarginV -> lower on screen)
    if (f.line2 && f.line2.trim() !== '') {
      const text2 = getPlainText(f.line2);
      lines.push(`Dialogue: 0,${startAss},${endAss},STYLE2,,0,0,0,,${text2}`);
    }
    
    return lines;
  }).join('\n');
  
  return header + events;
}

async function getVideoResolution(inputPath) {
  // Helper to get video width/height for ASS PlayRes (currently unused but good practice)
  try {
    const out = execSync(`ffprobe -v error -select_streams v:0 -show_entries stream=width,height -of csv=p=0 "${inputPath}"`).toString().trim();
    const [w, h] = out.split(',');
    return { width: parseInt(w), height: parseInt(h) };
  } catch (e) {
    return { width: 1920, height: 1080 };
  }
}

// -------------------------
// Main /render endpoint
// -------------------------
app.post('/render', async (req, res) => {
  
  try {
    // 0) Authorization check
    const headerSecret = req.header('X-Render-Secret');
    const bodySecret = req.body && req.body.render_secret;
    const provided = headerSecret || bodySecret || '';
    if (provided !== RENDER_SECRET) {
      return res.status(401).json({ status: 'error', error: 'unauthorized' });
    }

    const { job_id, video_url, frames, style, callback_url, watermark_url, plan_tier } = req.body || {};

    if (!video_url || !frames) {
      return res.status(400).json({ status: 'error', error: 'missing fields - require video_url and frames' });
    }

    const shouldAddWatermark = plan_tier === "free";

    // file paths
    const tmpDir = '/tmp';
    const inputPath = path.join(tmpDir, `in-${job_id}.mp4`);
    const assPath = path.join(tmpDir, `subs-${job_id}.ass`);
    const watermarkPath = path.join(tmpDir, `watermark-${job_id}.png`); 
    const outPath = path.join(tmpDir, `out-${job_id}.mp4`);

    // 1) Download the input video
    // This is wrapped in a try/catch for the 403 issue
    try {
        const writer = (await axios({ url: video_url, method: 'GET', responseType: 'stream' })).data;
        const outStream = fsSync.createWriteStream(inputPath);
        await new Promise((resolve, reject) => {
          writer.pipe(outStream);
          writer.on('end', resolve);
          writer.on('error', reject);
        });
    } catch (e) {
        console.error('Failed to download video:', e.message);
        return res.status(500).json({ status: 'error', error: 'Request failed with status code 403 or other download error for input video.' });
    }


    // 2) Download watermark image if needed
    let watermarkInput = null;
    if (shouldAddWatermark && watermark_url) {
        try {
            const logoWriter = (await axios({ url: watermark_url, method: 'GET', responseType: 'stream' })).data;
            const logoOutStream = fsSync.createWriteStream(watermarkPath);
            await new Promise((resolve, reject) => {
                logoWriter.pipe(logoOutStream);
                logoOutStream.on('close', resolve); // Use 'close' event for file stream
                logoWriter.on('error', reject);
            });
            watermarkInput = watermarkPath;
        } catch (e) {
            console.warn('Failed to download watermark image (Non-fatal, using text watermark):', e.message);
            // Non-fatal: just continue with text watermark
        }
    }

    // 3) Create ASS subtitles
    const ass = framesToAss(frames, style);
    await fs.writeFile(assPath, ass, 'utf8');

    // --- WATERMARK CONSTANTS ---
    const WATERMARK_TEXT = "AiVideoCaptioner";
    // ⭐ MODIFIED: Final Watermark Height set to 28px
    const WATERMARK_IMAGE_HEIGHT = 28; 
    const WATERMARK_TEXT_SIZE = 18; 
    const PADDING = 24; // Padding from video edges

    // 4) Build ffmpeg filter_complex
    let ffArgs;
    // ASS filter is the same whether we use image or text watermark, it's the last step
    const assFilter = `ass=filename=${assPath}:fontsdir=/app/fonts`;
    let filterComplex;
    let inputCount = 1; // Video is always input 0, watermark is input 1 if present

    if (shouldAddWatermark) {
        if (watermarkInput) {
            // Image Watermark setup (PNG input)
            // Input 0: Watermark Image; Input 1: Video
            
            // Filter 1: Scale watermark image, maintaining aspect ratio (-1)
            filterComplex = 
                `[0:v]scale=-1:${WATERMARK_IMAGE_HEIGHT}[wm_scaled];` + 
                // Filter 2: Overlay scaled watermark in the top-right corner
                `[1:v][wm_scaled]overlay=x=main_w-overlay_w-${PADDING}:y=${PADDING}[v_wm];`; 
            
            // Filter 3: Apply ASS subtitles to the watermarked video
            filterComplex += `[v_wm]${assFilter}[v]`;

            ffArgs = [
                '-y', 
                '-i', watermarkInput, // Input 0: Watermark Image
                '-i', inputPath, // Input 1: Video
                '-filter_complex', filterComplex,
                '-map', '[v]', '-map', '1:a?', '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '23', '-c:a', 'copy', outPath
            ];

        } else {
            // Text Watermark setup (Fallback if image download failed)
            // Input 0: Video
            const watermarkDrawText = 
              `drawtext=` +
              `fontfile='Lexend-Regular.ttf':` + 
              `text='${WATERMARK_TEXT}':` +
              `fontsize=${WATERMARK_TEXT_SIZE}:` + 
              `fontcolor=white@0.7:` +
              `x=main_w-tw-${PADDING}:` + 
              `y=${PADDING}[v_wm]`; 

            // Final Chain: [0:v] -> Watermark Drawtext -> ASS -> [v]
            filterComplex = `[0:v]${watermarkDrawText};[v_wm]${assFilter}[v]`;
            
            ffArgs = [
                '-y', 
                '-i', inputPath, // Input 0: Video
                '-filter_complex', filterComplex,
                '-map', '[v]', '-map', '0:a?', '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '23', '-c:a', 'copy', outPath
            ];
        }
    } else {
        // NO Watermark (Paid Tier)
        // Input 0: Video
        filterComplex = `[0:v]${assFilter}[v]`;

        ffArgs = [
            '-y', 
            '-i', inputPath, // Input 0: Video
            '-filter_complex', filterComplex,
            '-map', '[v]', '-map', '0:a?', '-c:v', 'libx264', '-preset', 'veryfast', '-crf', '23', '-c:a', 'copy', outPath
        ];
    }


    // 5) Run ffmpeg
    try {
      await runFFmpeg(ffArgs);
    } catch (ffErr) {
      console.error('ffmpeg failed:', ffErr);
      return res.status(500).json({ status: 'error', error: 'ffmpeg failed: ' + ffErr.message });
    }

    // 6) Upload result to GCS
    const destName = `renders/${job_id}-${Date.now()}.mp4`;
    let publicUrl;
    try {
      publicUrl = await uploadToGCS(outPath, destName);
    } catch (uerr) {
      console.error('upload failed:', uerr);
      return res.status(500).json({ status: 'error', error: 'upload failed: ' + uerr.message });
    }

    // 7) Optional callback to Bubble
    if (callback_url) {
      try {
        await axios.post(callback_url, {
          render_secret: RENDER_SECRET,
          job_id,
          status: 'success',
          video_url: publicUrl
        }, { timeout: 10000 });
      } catch (e) {
        console.warn('Callback failed (non-fatal):', e.message);
      }
    }

    // 8) Respond
    return res.json({ status: 'success', job_id, video_url: publicUrl });

  } catch (err) {
    console.error('Server error:', err);
    return res.status(500).json({ status: 'error', error: err.message || String(err) });
  }
});

const port = process.env.PORT || 8080;
app.listen(port, () => console.log('listening on', port));
